### ISSUE TITLE
请教能否测试体验提供下意见

### ISSUE THREAD

**Issue by codiggermkt** [gatieme/LDD-LinuxDeviceDrivers#9]
无敌哥，请教能否测试体验提供下意见
我们开发了个私人应用的全流程生态平台-codigger,Codigger不仅实现了“我的数据我做主”，也提供了创新的、划时代的开发、运营、交易和使用应用的模式，让私人应用所有类型的用户都大大降低了成本，提高了效率。
Codigger提供了丰富多样的module和私人应用，为module和私人应用的开发、运营、交易和使用用户通过“我的数据”获得收益，同时也为寻找数据的用户提供大量的优质数据。
您有没有兴趣了解下？

**Comment by gatieme** [comment]
暂时没有兴趣，感谢
